<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mini Site</title>
</head>
<body>
    <div class="menu">
        <a href="/index.php?controller=books&amp;action=list">Books</a>
        <a href="/index.php?controller=feedback">Feedback messages</a>
        <a href="/index.php?controller=security">Logout</a>
    </div>

    <hr>


    <?//='flash message';//вывод сообщения о добавлении книги?>

    <div class="content">
        <?=$content?>

    </div>

    <hr>

    <footer>
        Some footer
    </footer>

</body>
</html>